# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20171218_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoperation',
            name='operation_type',
            field=models.CharField(choices=[('stock_input', 'Stock Input'), ('stock_output', 'Stock Output')], max_length=20, unique=True),
        ),
    ]
